from langchain.agents import create_agent

from app.agents.promots import REQUIREMENTS_AGENT_SYSTEM_PROMPT
from app.agents.response_models import RequirementsAgentResponseModel
from app.agents.tools.flight_tools import search_flight_availability